# Generated by Django 3.1.7 on 2021-03-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='image',
            field=models.ImageField(default=0, upload_to='postings/%Y%M%d'),
            preserve_default=False,
        ),
    ]
