# Generated by Django 3.1.7 on 2021-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predict',
            name='sodium_mg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
