# Generated by Django 3.1.7 on 2021-03-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20210327_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='sodium_mg',
            new_name='accuracy',
        ),
    ]
